version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./config/application-dev.yml:/app/config/application-dev.yml
      - type: bind
        source: ./logs
        target: /app/logs
    restart: always
